[package]
name = "Rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.1"
num-bigint = "0.4.4"
num-traits = "0.2.18"
rand = "0.8.5"

[[bin]]
name = "Rust"
path = "main.rs"
